---
- name: create file
  hosts: all
  vars:
   arrayname:
     - msg1
     - msg2
     - msg3
  tasks:
        - name: creating an empty file
          shell:
           msg: "Hi {{ msg1 }}" 
           msg: "Hi {{ msg2 }}" 
           msg: "Hi {{ msg3 }}" 
           
